### ISSUE TITLE
QC Logic for post assembly quality controls

### ISSUE THREAD

**Issue by bfjia** [Public-Health-Bioinformatics/cpo-pipeline#15]
determine PASS/FAIL of post assembly quality controls using QUAST and BUSCO.

**Comment by bfjia** [comment]
How should we determine what the PASS cutoff is for QUAST results?

My ideas: 
Total length of the assembly vs Reference length
GC (%) of the assembly vs Reference GC (%)

**Comment by dfornika** [comment]
I'd expect that the assembly length vs reference length would be the more useful metric, and probably easier to draw sensible thresholds around.
