### ISSUE TITLE
Determine 'Expected species' automatically

### ISSUE THREAD

**Issue by dfornika** [Public-Health-Bioinformatics/cpo-pipeline#4]
Our sample naming conventions include a short coded organism name. eg:

```
'Eco': 'Escherichia coli'
'Cfr': 'Citrobacter freundii'
'Kpn': 'Klebsiella pneumoniae'
...etc...
```

We may be able to make the 'Expected species' input parameter optional. We could attempt to parse the sample ID to determine the expected species, but only if an expected species isn't provided as an input parameter.

**Comment by ddooley** [comment]
Are you talking about BCCDC sample naming conventions?  Suggests that an install of the program could have a lookup table suited to the institution running it.

**Comment by dfornika** [comment]
Yes, those are our internal naming conventions. That's a good suggestion.

**Comment by dfornika** [comment]
I've decided not to implement this because it's too specific to our naming convention and would be difficult to generalize well.

I've added an optional parameter that accepts an NCBI taxonomy ID for the 'expected organism'.
