### ISSUE TITLE
Configuration error: databases/abricate_cpo_plasmid_db

### ISSUE THREAD

**Issue by dfornika** [Public-Health-Bioinformatics/cpo-pipeline#47]
I'm seeing error messages in the logs when running the pipeline:

```json
{"analysis_id": "114e1038-f7a3-4234-b7b0-acc6f1881b1d", "sample_id": "BC19A227A", "pipeline_version": "0.1.0", "timestamp": "2019-05-02T00:22:14.656615+00:00", "configuration_attribute": "databases/abricate_cpo_plasmid_db", "event": "configuration_failed", "level": "error"}
{"analysis_id": "dd5ea069-4e46-40c1-b5b9-5cc2950cd289", "sample_id": "BC19A228A", "pipeline_version": "0.1.0", "timestamp": "2019-05-02T00:25:00.525266+00:00", "configuration_attribute": "databases/abricate_cpo_plasmid_db", "event": "configuration_failed", "level": "error"}
...
```

Suggesting that the `abricate_cpo_plasmid_db` config value is not being loaded correctly.

**Comment by DiDigsDNA** [comment]
I'll take a look at this.

**Comment by DiDigsDNA** [comment]
I think the problem is happening here:
https://github.com/Public-Health-Bioinformatics/cpo-pipeline/blob/a5c81ef12880c22e027d977ed2778543e8cca9e8/cpo_pipeline/resistance/pipeline.py#L98

We're checking that `carbapenemases` exists as a path but we should be checking inside `abricate_datadir`.

**Comment by dfornika** [comment]
Yes, I think that's right. Could you submit a pull-request?
