### ISSUE TITLE
Merge Pipeline Phases Into One Unified Pipeline

### ISSUE THREAD

**Issue by dfornika** [Public-Health-Bioinformatics/cpo-pipeline#8]
We currently have three 'phases' for the pipeline:

1.  assembly
2. typing
3. tree

These can be combined into a single pipeline, which will simplify the end-user's task of running the pipeline.

**Comment by bfjia** [comment]
currently, the assembly and typing portion only supports single isolates. Whereas the 'tree' module requires the use of multiple isolates

**Comment by dfornika** [comment]
Good point. It's likely that the assembly & typing phases will be run routinely as soon as new samples arrive. Then the tree phase would be run more sporadically. It might make sense to keep those parts separate in some way.
